auto: true
server: true
markdown: kramdown
title: "idea-path"
url: "https://note.idea-path.app"
author: ALNAME
baseurl: "/"

#markdown
defaults:
  - scope:
      path: "Original/user00"
    values:
      author:
        name: "ALNAME"
  - scope:
      path: "Original/user01"
    values:
      author:
        name: "黒い兄"
        site_address: http://homepage2.nifty.com/blackbros/
        site_title: "がんばり過ぎない"
  - scope:
      path: "Original/user02"
    values:
      author:
        name: "赤い流星"
  - scope:
      path: "Original/user03"
    values:
      author:
        name: "八尺8r"
        site_address: "http://www.yasaka3net.qcweb.jp/yasaka/index.shtml"
        site_title: "やぼーのホームページ"
  - scope:
      path: "Original/user04"
    values:
      author:
        name: "どこぞ"
  - scope:
      path: "Original/user05"
    values:
      author:
        name: "きさまる"

#image
defaults:
  - scope:
      path: "static/image/original/user0"
    values:
      artist: "ALNAME"
  - scope:
      path: "static/image/original2nd/user0"
    values:
      artist: "ALNAME"