auto: true
server: true
markdown: kramdown
title: "idea-path"
url: "https://alname.github.io/"
author: ALNAME
baseurl: "/idea-path"
defaults:
  -
    scope:
      path: "user01"
      type: "pages"
    values:
      author:
        name: "黒い兄"
